title: Problem Solving Book
author: Prog Theta
description: Solving Some Catagories Problem With Hints.
theme: jekyll-theme-minimal
markdown: kramdown
highlighter: rouge
show_downloads: false
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
